app:
  port: 80
db:
  hostname: "127.0.0.1"
  database: "books"
  username: "books"
  password: "XKMLkcpB2LazRTdd"
  port: 3306
  charset: "utf8mb4"
jwt:
  realm: "app"
  key: "secret key"

# 小程序
miniprogram:
  appid: "wx59511f005ad46d8b"
  appsecret: "dfe491108ea9b8299a26541080aa366f"
